### ISSUE TITLE
Build a community around the TU Delft Open Science MOOC

### ISSUE THREAD

**Issue by AleCandian** [open-life-science/ols-5#13]
Project Lead: @AleCandian @lwbwalma

Mentor: @pherterich

Welcome to OLS-5! This issue will be used to track your project and progress during the program. Please use this checklist over the next few weeks as you start Open Life Science program :tada:.

***

Week 1 (week starting 28 February 2022): Meet your mentor!
- [x] Meet mentor for 30 minutes 
- [x] Create an account on [GitHub](https://github.com)
- [x] Check if you have access to the HackMD notes set up for your meetings with your mentor
- [x] Prepare to meet your mentor(s) by completing a short homework provided in your shared notes
- [x] Complete **your own copy** of the [open leadership self-assessment](https://docs.google.com/document/d/1oQgdfj4lPnypAyb9_Ba0Zt7E8J5L6qMvuKwu0wgQsjs/edit?usp=sharing) and share it to your mentor 
  If you're a group, each teammate should complete this assessment individually. This is here to help you set your own personal goals during the program. No need to share your results, but be ready to share your thoughts with your mentor.
- [x] Make sure you know when and how you'll be meeting with your mentor.

Before Week 2 (week starting 7 March 2022): Cohort Call (Welcome to Open Life Science!)
- [x] Attend call or catch up via YouTube
- [x] Create an issue on the [OLS-5 GitHub repository](https://github.com/open-life-science/ols-5/issues/new) for your OLS work and share the link to your mentor.
- [x] Draft a brief vision statement using your goals

  [This lesson](https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/stating-your-project-vision/) from the Open Leadership Training Series (OLTS) might be helpful

- [x] Leave a comment on this issue with your draft vision statement & be ready to share this on the call
- [x] Check the [Syllabus](https://openlifesci.org/ols-5) for notes and connection info for all the cohort calls.

Before Week 3 (week starting 14 March 2022): Meet your mentor!
- [x] Meet mentor
- [x] Look up two other projects and comment on their issues with feedback on their vision statement
- [x] Complete this [compare and contrast assignment](https://docs.google.com/document/d/1ukvqDRIYfvCapVMdE5hWP-0MkLNJ9T65X43O7F336Ac/edit?usp=sharing) about current and desired community interactions and value exchanges
- [x] Complete your Open Canvas ([instructions](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas/), [canvas](https://docs.google.com/presentation/d/1MeJo0TyuMg_waLk1J4q9y1aAqKNMuRBlnmxEChSz-cQ/edit?usp=sharing))
- [x] Share a link to your Open Canvas in your GitHub issue
- [x] Start your [Roadmap](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/)
- [x] Comment on your issue with your draft Roadmap
- [x] Suggest a cohort name at the bottom of the shared notes and vote on your favorite with a +1

Before Week 4: Cohort Call (Tooling and roadmapping for Open projects)
- [x] Attend call or catch up via YouTube
- [x] Look up two other projects and comment on their issues with feedback on their open canvas.

Week 5 and later
- [x] Meet mentor
- [x] Create a GitHub repository for your project
- [x] Add the link to your repository in your issue
- [x] Use your canvas to [start writing a `README.md` file](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/), or landing page, for your project
- [x] Link to your README in a comment on this issue
- [x] Add an [open license](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/sharing-your-work-in-the-open/) to your repository as a file called `LICENSE.md`
- [x] Add a [Code of Conduct](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-a-code-of-conduct/) to your repository as a file called `CODE_OF_CONDUCT.md`
- [ ] Invite new contributors to into your work!

This issue is here to help you keep track of work as you start Open Life Science program. Please refer to the [OLS-5 Syllabus](https://openlifesci.org/ols-5) for more detailed weekly notes and assignments past week 4.

Week 6 
- [x] Attend call or catch up via YouTube

Week 7
- [x] Meet mentor

Week 8
- [x] Attend call or catch up via YouTube

Week 9
- [ ] Meet mentor

Week 10
- [x] Attend call or catch up via YouTube

Week 11
- [x] Meet mentor

Week 12
- [x] Attend call or catch up via YouTube

Week 13
- [x] Meet mentor

Week 14
- [x] Attend call or catch up via YouTube

Week 15
- [x] Meet mentor

**Comment by AleCandian** [comment]
Here our vision: 
We are working with a team of teachers and trainers at TU Delft (NL) to teach a MOOC that engages participants with the open science communities so that students and researchers  feel motivated to join the Open Science movement and change the way we do science.

**Comment by AleCandian** [comment]
Hello! here you can find our Open Canvas: [https://docs.google.com/presentation/d/17EVfrS5zsFhHGR4LggNFYAZ9RHS6PTPzn2Y6Jt_3Dxc/edit?usp=sharing](url)

Looking forward to feedback and ideas :)

**Comment by AleCandian** [comment]
After some editing with Hemingway, this is the revised Vision statement:

"We work with a team of teachers  at TU Delft to run a Massive Online Open Course (MOOC) on Open Science. We want to design  an engaging course that shows the participants the advantages of Open Science and motivate them to join and contribute to the Open Science movement."

**Comment by evelyngreeves** [comment]
Hi @AleCandian! Your vision and project canvas are very clear, well done 🎉

As part of my project I'm also hoping to engage more participants with our open science community following our training course(s). Do you have any ideas about how to encourage people to engage and minimise dropout? We have the same problem of a few people engaging actively and the rest dropping off the radar a bit. Interested to hear your thoughts!

**Comment by lwbwalma** [comment]
Hi @evelyngreeves! Thank you for the compliments on our canvas and vision :blush:! @AleCandian and I are still brainstorming what could minimize dropout. We are currently focused on the content of our course, trying to make it more engaging by giving relevant examples and also adding feedback videos from our teachers after each course module has finished. Moreover, we want to make the discussion forums we use more interactive (for example by asking students to reply to a previous post from another student). Still in the first stages of thinking about this, very curious to hear your thoughts and ideas as well :smiley:

**Comment by fredbelliard** [comment]
Hi @AleCandian and @lwbwalma I like your vision very much :-)  I see some overlap with what we are trying to do with TU Delft OPEN Publishing. Engagement is one of our challenges so I'll be more than happy to hear more about the course. Surely we could get some tips from you ladies.

**Comment by lwalma** [comment]
Hi @fredbelliard! Thank you for your compliments 😃! For sure we would be happy to talk about our course and also learn more about your awesome project! We'll be in touch 😄

**Comment by AleCandian** [comment]
Our Roadmap: https://docs.google.com/document/d/1Q1W9wEz-sdAQ0xRujNaaIlUtDKsEHCQ98U1Xrf3jSR4/edit# also in the repo of our project
