### ISSUE TITLE
Training Latin American scientists’ community to create high-quality open journals with good editorial standards

### ISSUE THREAD

**Issue by jvillcavillegas** [open-life-science/ols-5#20]
Project Team:  
Jose Luis Villca Villegas [jvillcavillegas](https://github.com/jvillcavillegas)
Nelson Franco Condori Salluco [NELSON-FRANCO](https://github.com/NELSON-FRANCO)
Camila Alejandra Gomez Verduguez [cami226](https://github.com/Cami226)
Danae Carelis Davila Espinoza [danae24](https://github.com/Cami226)
Andre Alvaro Vargas Aguilar [andre-vargas-de](https://github.com/andre-vargas-de)

Mentor:  
Alexander Martinez Mendez [mxrtinez](https://github.com/mxrtinez)
Belen Ticona

Welcome to OLS-5! This issue will be used to track your project and progress during the program. Please use this checklist over the next few weeks as you start Open Life Science program :tada:.

***

Week 1 (week starting 28 February 2022): Meet your mentor!
- [x] Meet mentor for 30 minutes 
- [x] Create an account on [GitHub](https://github.com)
- [x] Check if you have access to the HackMD notes set up for your meetings with your mentor
- [x] Prepare to meet your mentor(s) by completing a short homework provided in your shared notes
- [x] Complete **your own copy** of the [open leadership self-assessment](https://docs.google.com/document/d/1oQgdfj4lPnypAyb9_Ba0Zt7E8J5L6qMvuKwu0wgQsjs/edit?usp=sharing) and share it to your mentor 
  If you're a group, each teammate should complete this assessment individually. This is here to help you set your own personal goals during the program. No need to share your results, but be ready to share your thoughts with your mentor.
- [x] Make sure you know when and how you'll be meeting with your mentor.

***

Before Week 2 (week starting 7 March 2022): Cohort Call (Welcome to Open Life Science!)
- [x] Attend call or catch up via YouTube
- [x] Create an issue on the [OLS-5 GitHub repository](https://github.com/open-life-science/ols-5/issues/new) for your OLS work and share the link to your mentor.
- [x] Draft a brief vision statement using your goals
  [This lesson](https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/stating-your-project-vision/) from the Open Leadership Training Series (OLTS) might be helpful
- [x] Leave a comment on this issue with your draft vision statement & be ready to share this on the call
- [x] Check the [Syllabus](https://openlifesci.org/ols-5) for notes and connection info for all the cohort calls.

***

Before Week 3 (week starting 14 March 2022): Meet your mentor!
- [x] Meet mentor
- [] Look up two other projects and comment on their issues with feedback on their vision statement
- [x] Complete this [compare and contrast assignment](https://docs.google.com/document/d/1ukvqDRIYfvCapVMdE5hWP-0MkLNJ9T65X43O7F336Ac/edit?usp=sharing) about current and desired community interactions and value exchanges
- [x] Complete your Open Canvas ([instructions](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas/), [canvas](https://docs.google.com/presentation/d/1MeJo0TyuMg_waLk1J4q9y1aAqKNMuRBlnmxEChSz-cQ/edit?usp=sharing))
- [x] Share a link to your Open Canvas in your GitHub issue
- [x] Start your [Roadmap](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/)
- [x] Comment on your issue with your draft Roadmap
- [x] Suggest a cohort name at the bottom of the shared notes and vote on your favorite with a +1

***

Before Week 4: Cohort Call (Tooling and roadmapping for Open projects)
- [x] Attend call or catch up via YouTube
- [x] Look up two other projects and comment on their issues with feedback on their open canvas.

***

Week 5 and later
- [x] Meet mentor
- [x] Create a GitHub repository for your project
- [x] Add the link to your repository in your issue
- [x] Use your canvas to [start writing a `README.md` file](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/), or landing page, for your project
- [x] Link to your README in a comment on this issue
- [x] Add an [open license](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/sharing-your-work-in-the-open/) to your repository as a file called `LICENSE.md`
- [x] Add a [Code of Conduct](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-a-code-of-conduct/) to your repository as a file called `CODE_OF_CONDUCT.md`
- [x] Invite new contributors to into your work!

This issue is here to help you keep track of work as you start Open Life Science program. Please refer to the [OLS-5 Syllabus](https://openlifesci.org/ols-5) for more detailed weekly notes and assignments past week 4.

***

Week 6 
- [x] Attend call or catch up via YouTube

***

Week 7
- [x] Meet mentor

***

Week 8
- [x] Attend call or catch up via YouTube

***

Week 9
- [x] Meet mentor

***

Week 10
- [x] Attend call or catch up via YouTube

***

Week 11
- [x] Meet mentor

***

Week 12
- [x] Attend call or catch up via YouTube

***

Week 13
- [x] Meet mentor

***

Week 14
- [x] Attend call or catch up via YouTube

***

Week 15
- [x] Meet mentor

**Comment by jvillcavillegas** [comment]
Link to our [Open Canvas Proyect](https://docs.google.com/presentation/d/1rm_IwK17WmaLcspNflcy_bBnWjLiMtuGYFE8Xp9moqw/edit#slide=id.p1)

[Editorial Project Canvas](https://user-images.githubusercontent.com/82187040/160299142-693b0321-4f4a-4fc3-af1e-294b7a7289b3.jpg)

**Comment by fredbelliard** [comment]
Hi all, I am eager to hear more about your project and about your approach.  

Part of my work is to make sure that new open-access journals that we launch include a solid plan, a long term vision and very good editorial standards. Those are crucial for the sustainability and reputation of the journals.

**Comment by jvillcavillegas** [comment]
Hi Fred Belliard, We want to know more about you, we saw your OLS proposal, we would like to know more about you and your project, could we meet online up one of these days via zoom or other plataform?

**Comment by jvillcavillegas** [comment]
We wanna know more about you and your proyect!!! We wanna know if it is
possible a meeting in this week that is coming!!! We wait your answers

**Comment by fredbelliard** [comment]
@jvillcavillegas  I am unavailable this week and the week after (holiday period). What about the week of 2 May (Mon-Wed)? I am based in the Amsterdam time zone and can send you a zoom meeting invite.

**Comment by jvillcavillegas** [comment]
Hi Fred , We want to know you as soon as possible, If you could at 5 of May , please let me know it. 
Considering your amsterdam time zone, we are agree to 10 or 11 p. m. Amsterdam Zone
We wait your answers
Pd: We wanna know your email to write you directly please

**Comment by fredbelliard** [comment]
Hola Jose, 
contact me at f.belliard@tudelft.nl so we can arrange a time. Thanks

**Comment by eirinibotsari** [comment]
What a cool project!! I am curious how it is progressing!

**Comment by eirinibotsari** [comment]
What an on point initiative!! I am super curious about the progress and your planing!
