### ISSUE TITLE
An Incomplete History of Research Ethics

### ISSUE THREAD

**Issue by Ismael-KG** [open-life-science/ols-5#3]
Project Lead: @Ismael-KG

Mentor: @Lisanna

Welcome to OLS-5! This issue will be used to track your project and progress during the program. Please use this checklist over the next few weeks as you start Open Life Science program :tada:.

***

Week 1 (week starting 28 February 2022): Meet your mentor!
- [x] Meet mentor for 30 minutes 
- [x] Create an account on [GitHub](https://github.com)
- [x] Check if you have access to the HackMD notes set up for your meetings with your mentor
- [x] Prepare to meet your mentor(s) by completing a short homework provided in your shared notes
- [x] Complete **your own copy** of the [open leadership self-assessment](https://docs.google.com/document/d/1oQgdfj4lPnypAyb9_Ba0Zt7E8J5L6qMvuKwu0wgQsjs/edit?usp=sharing) and share it to your mentor 
  If you're a group, each teammate should complete this assessment individually. This is here to help you set your own personal goals during the program. No need to share your results, but be ready to share your thoughts with your mentor.
- [x] Make sure you know when and how you'll be meeting with your mentor.

Before Week 2 (week starting 7 March 2022): Cohort Call (Welcome to Open Life Science!)
- [x] Attend call or catch up via YouTube
- [x] Create an issue on the [OLS-5 GitHub repository](https://github.com/open-life-science/ols-5/issues/new) for your OLS work and share the link to your mentor.
- [x] Draft a brief vision statement using your goals

  [This lesson](https://mozilla.github.io/open-leadership-training-series/articles/introduction-to-open-leadership/stating-your-project-vision/) from the Open Leadership Training Series (OLTS) might be helpful

- [x] Leave a comment on this issue with your draft vision statement & be ready to share this on the call
- [x] Check the [Syllabus](https://openlifesci.org/ols-5) for notes and connection info for all the cohort calls.

Before Week 3 (week starting 14 March 2022): Meet your mentor!
- [x] Meet mentor
- [x] Look up two other projects and comment on their issues with feedback on their vision statement
- [ ] Complete this [compare and contrast assignment](https://docs.google.com/document/d/1ukvqDRIYfvCapVMdE5hWP-0MkLNJ9T65X43O7F336Ac/edit?usp=sharing) about current and desired community interactions and value exchanges
- [x] Complete your Open Canvas ([instructions](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/develop-an-open-project-strategy-with-open-canvas/), [Ismael's canvas](https://docs.google.com/presentation/d/1UHJr2dz0e9xTn1MV6lulhfkGh3Y-WyY5W_m6yPZ3Apg/edit?usp=sharing))
- [x] Share a link to your Open Canvas in your GitHub issue
- [x] Start your [Roadmap](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/)
- [ ] Comment on your issue with your draft Roadmap
- [x] Suggest a cohort name at the bottom of the shared notes and vote on your favorite with a +1

Before Week 4: Cohort Call (Tooling and roadmapping for Open projects)
- [x] Attend call or catch up via YouTube
- [ ] Look up two other projects and comment on their issues with feedback on their open canvas.

Week 5 and later
- [x] Meet mentor
- [x] Create a GitHub repository for your project
- [ ] Add the link to your repository in your issue
- [x] Use your canvas to [start writing a `README.md` file](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/write-a-great-project-readme/), or landing page, for your project
- [ ] Link to your README in a comment on this issue
- [x] Add an [open license](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/sharing-your-work-in-the-open/) to your repository as a file called `LICENSE.md`
- [x] Add a [Code of Conduct](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/write-a-code-of-conduct/) to your repository as a file called `CODE_OF_CONDUCT.md`
- [ ] Invite new contributors to into your work!

This issue is here to help you keep track of work as you start Open Life Science program. Please refer to the [OLS-5 Syllabus](https://openlifesci.org/ols-5) for more detailed weekly notes and assignments past week 4.

Week 6 
- [x] Attend call or catch up via YouTube

Week 7
- [x] Meet mentor

Week 8
- [x] Attend call or catch up via YouTube

Week 9
- [x] Meet mentor

Week 10
- [x] Attend call or catch up via YouTube

Week 11
- [x] Meet mentor

Week 12
- [x] Attend call or catch up via YouTube

Week 13
- [x] Meet mentor

Week 14
- [x] Attend call or catch up via YouTube

Week 15
- [x] Meet mentor

**Comment by Ismael-KG** [comment]
**Vision statement**

> Through community-led dialogue, rigorous research, and care for the social impact of science, An Incomplete History of Research Ethics provides a compilation of thought-provoking stories from our shared past. Using diverse and engaging formats, we enable varied audiences inside and out of knowledge-production to conduct and critique research as a product of its social context (drafted [here](https://github.com/Ismael-KG/An_Incomplete_History_of_Research_Ethics/blob/main/Were_there_a_pitch_deck.md#Vision)).

**Comment by AleCandian** [comment]
Hi Ismael, I like your vision statement: It makes me very curious to know more about your project :) I notice you tried to compress a  lot of meaning within the short format of the vision statement and somehow for me this makes the statement a little bit obscure. For example which are the "diverse and engaging formats"? who are  these "varied audiences inside and out of knowledge-production"? Also for knowledge-production do you mean universities/research centers only? My suggestion would be to use maybe simpler words :)

**Comment by Ismael-KG** [comment]
Ah, this is great, thanks @AleCandian! @Lisanna made similar points when I shared it with her last week. I'll come back to it, but this is my first re-draft:

>Through community-led dialogue, rigorous research, and care for the social impact of science, _An Incomplete History of Research Ethics_ provides a compilation of thought-provoking stories from our shared past. Using visually engaging formats and delivering stories in short and long-form, we enable audiences from across the research ecosystem to conduct and critique research as a product of its social context.

The tricky thing is I don't want to exclude "industry" as a potential user of _An Incomplete History of Research Ethics_. I hope "research ecosystem" is inclusive enough, but less obscure than "knowledge-production"!

**Comment by vborghe** [comment]
Hi @Ismael-KG! What a great idea and set up you have here! I feel your pain in trying to explain in simple (yet inclusive) words such a complex multidimensional space 😄  I truly look forward to enjoy (and learn from) some of the stories you'll share!

**Comment by Ismael-KG** [comment]
Most kind! I just made some changes using [hemingway](https://hemingwayapp.com) and I think I am happy with this version:

>_An Incomplete History of Research Ethics_ provides a compilation of thought-provoking stories from our shared past. The project relies on community-led dialogue and rigorous research. Stories are delivered in short- and long-form, using accessible and fun formats. Through story-telling, we promote reflexivity across the research ecosystem.

**Comment by Ismael-KG** [comment]
### Canvas

https://docs.google.com/presentation/d/1UHJr2dz0e9xTn1MV6lulhfkGh3Y-WyY5W_m6yPZ3Apg/edit?usp=sharing

**Comment by Ismael-KG** [comment]
**README**

https://github.com/Ismael-KG/An_Incomplete_History_of_Research_Ethics/blob/main/README.md

**Comment by Cel31** [comment]
Hello! It is a brilliant idea to use stories to think of research ethics, cannot wait to hear more from your project!

**Comment by Ismael-KG** [comment]
Hey @AleCandian @vborghe and @Cel31 – for your time commenting on this issue – specifically on the vision statement – would it be okay for me to acknowledge you in the project's [contributors](https://github.com/Ismael-KG/An_Incomplete_History_of_Research_Ethics/blob/main/Contributors.md) document? (Perfectly fine if not!)

**Comment by Cel31** [comment]
Hi! Yes of course, I am really honoured in fact :)

**Comment by AleCandian** [comment]
Same here, thank you! :)

**Comment by Ismael-KG** [comment]
Amazing, you should have invites in your emails (I think they go there!)

**Comment by vborghe** [comment]
Extremely happy and honored as well! Please let me know if there is anything concrete I could help with at this stage: I'd like to fully deserve it 😄

**Comment by Ismael-KG** [comment]
@vborghe @Cel31 @AleCandian – I want to work on a speedblog post for OLS. If I do that, would you be kind enough to review it? I haven't given myself a deadline for this yet, but it shouldn't demand too much of your time!

It will probably capture some of what I said during [my OLS-5 graduation](https://www.youtube.com/watch?v=8_26-PYJaFw) and [at LSE's _Knowledge Beyond Boundaries_ conference](https://doi.org/10.5281/zenodo.6616736). Let me know!

And once that is done, I think I will close this issue!

**Comment by Cel31** [comment]
Hello,

Sure, I ll be happy to participate.

Best,
Céline

**Comment by AleCandian** [comment]
> @vborghe @Cel31 @AleCandian – I want to work on a speedblog post for OLS. If I do that, would you be kind enough to review it? I haven't given myself a deadline for this yet, but it shouldn't demand too much of your time!

Count on me.

**Comment by Ismael-KG** [comment]
Here we are! A very speedy draft!

Please take a look and suggest edits. I'll acknowledge these as _communications_ contributions as per [Protocol 3](https://github.com/Ismael-KG/An_Incomplete_History_of_Research_Ethics/blob/main/Protocols.md#Protocol-3-Contribution-Types).

https://docs.google.com/document/d/1EGVUqYRzatp1v4jbCNXFBDquJ6bE1D7VXsJP5ESFJaU/edit?usp=sharing

If you work best with deadlines in mind, let's say Saturday 2nd July, but that's not too important!

**Comment by Ismael-KG** [comment]
Just to confirm the speed blog was up [on 8th August](https://openlifesci.org/posts/2022/08/08/An-Incomplete-History-Of-Research-Ethics/) and I received the certificate today! I'll go ahead and close this issue now. Thanks all!

[OLS-5 – Ismael KG.pdf](https://github.com/open-life-science/ols-5/files/9453080/OLS-5.Ismael.KG.pdf)
